# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Maps' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Maps
  pod 'Swinject'
  pod 'SnapKit'
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftLint'
  pod 'GoogleMaps'
  pod 'RxCoreLocation', '~> 1.3.1'
  
  target 'MapsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
